language: csharp
solution: SAP1EMU.sln
mono: none
dotnet: 3.1
script:
  - dotnet build SAP1EMU.sln
  - dotnet test SAP1EMU.Lib.Test -v n --no-build --collect:"XPlat Code Coverage"
  - dotnet test SAP1EMU.CLI.Test -v n --no-build --collect:"XPlat Code Coverage"
  - dotnet test SAP1EMU.Assembler.Test -v n --no-build --collect:"XPlat Code Coverage"
  - dotnet test SAP1EMU.Engine.Test -v n --no-build --collect:"XPlat Code Coverage"

after_success:
  - bash <(curl -s https://codecov.io/bash)
