// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAP1EMU.GUI.Contexts;

namespace SAP1EMU.GUI.Migrations
{
    [DbContext(typeof(Sap1EmuContext))]
    [Migration("20201204061524_AddedBinaryTable_v2")]
    partial class AddedBinaryTable_v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SAP1EMU.GUI.Models.CodeSubmit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("submitted_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("CodeStore");
                });

            modelBuilder.Entity("SAP1EMU.GUI.Models.EmulationSessionMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConnectionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmulationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SessionEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SessionStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EmulationSessionMaps");
                });

            modelBuilder.Entity("SAP1EMU.GUI.Models.SAP2BinaryPacket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmulationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EmulationSessionMapId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmulationSessionMapId");

                    b.ToTable("SAP2BinaryStore");
                });

            modelBuilder.Entity("SAP1EMU.GUI.Models.SAP2CodePacket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmulationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EmulationSessionMapId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmulationSessionMapId");

                    b.ToTable("SAP2CodeStore");
                });

            modelBuilder.Entity("SAP1EMU.GUI.Models.SAP2BinaryPacket", b =>
                {
                    b.HasOne("SAP1EMU.GUI.Models.EmulationSessionMap", "EmulationSessionMap")
                        .WithMany()
                        .HasForeignKey("EmulationSessionMapId");
                });

            modelBuilder.Entity("SAP1EMU.GUI.Models.SAP2CodePacket", b =>
                {
                    b.HasOne("SAP1EMU.GUI.Models.EmulationSessionMap", "EmulationSessionMap")
                        .WithMany()
                        .HasForeignKey("EmulationSessionMapId");
                });
#pragma warning restore 612, 618
        }
    }
}
