name: .NET Core

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.202
    - name: Install dependencies
      run: dotnet restore SAP1EMU.Lib.Test
    - name: Build
      run: dotnet build --configuration Release --no-restore SAP1EMU.Lib.Test
    - name: Test
      run: dotnet test --no-restore --verbosity normal SAP1EMU.Lib.Test
